---
title: "PCA_on_new_genes_with_all_groups"
author: "Vamshi"
date: "7/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load required packages
require(data.table)
require(caret)
require(MLeval)
require(glmnet)
require(ROCR)
require(tidyverse)
require(MethylIT)
require(ComplexHeatmap)
require(circlize)
require(psych)

# directories
#data_dir = file.path("..", "..", "data")
result_dir = file.path("..", "..", "results")
p_dir = file.path(result_dir, "Plots")

# load data
data_f = read_csv("/Users/sd587/Dropbox (Partners HealthCare)/Thurman RNA-Seq/2021 DMD-DM1 samples/Data/PCA_new_genes_all_groups.csv")
ddPCR_r2 = setDT(data_f)
head(ddPCR_r2)
```





# Preprocessing
```{r}
# create prediction label
ddPCR_r2[, group := map(strsplit(ID, "-"), ~.x[1]) %>% unlist()]
ddPCR_r2[, group := factor(group)]
```

```{r}

# splite data into training and testing by 75:25
set.seed(123)
train_idex = createDataPartition(ddPCR_r2$group, p = .75, list = FALSE)
train = ddPCR_r2[train_idex, ]
test = ddPCR_r2[-train_idex, ]

```

```{r}
# normalization
# non-numeric predictors are allowed but will be ignored.
# method = "zv" identifies numeric predictor columns with a single value 
# (i.e. having zero variance) and excludes them from further calculations. 
train_proc = preProcess(train, method = c("center", "scale", "zv"), verbose = TRUE)
train_n = predict(train_proc, train)
head(train_n)
```


```{r}
# feature correlation analysis
train_cor = cor(train_n[, c(-1, -6)])
train_cor %>% 
  Heatmap(
    col = colorRamp2(c(-1, 0, 1), c("#0C6291", "#FBFEF9", "#A63446")),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.1f", train_cor[i, j]), x, y, gp = gpar(fontsize = 10))
})

pairs.panels(train_n[, c(-1, -6)],
             gap = 0,
             bg = c("red", "blue")[train_n$group],
             pch=21)


# 
# require(AppliedPredictiveModeling)
# require(lattice)
# transparentTheme(trans = .4)
# caret::featurePlot(x = ddPCR_n[, 2:6], 
#             y = ddPCR_n$group,
#             plot = "pairs")


```

```{r}
# step by step
# PCA
set.seed(1234)
train_pca11 = predict(
  preProcess(train, method = c("center", "scale", "pca"), verbose = TRUE),
  train
)   
View(train_pca11)
#view(train_var_dt)

```

```{r}

require(factoextra)
train_pca2 = prcomp(train[, c(-1, -6)], scale = TRUE, center = TRUE)
#view(train_pca2)
train_var = get_pca_var(train_pca2)
#view(train_var)
train_var$contrib
#view(train_var$contrib)

```

```{r}

train_var_dt = train_var$contrib[, 1:4] %>% as.data.frame()
setDT(train_var_dt)
train_var_dt[, exon := rownames(train_var$contrib)]
train_var_dt = melt(train_var_dt, id.vars = "exon", 
                    variable.name = "PC", value.name = "contribution")
```

```{r}
require(ggthemes)
ggplot(train_var_dt, aes(x = PC, y = exon)) +
  geom_point(aes(fill = contribution, size = contribution),
             colour="black",pch=21) +
  theme_few() +
  scale_fill_gradient(low = "yellow", high = "red", na.value = NA) +
  scale_size(range = c(1,10))

```

```{r}

require(cluster)
require(ggfortify)
ggplot(data = train_pca11, aes(x = PC1, y = PC2, col = group, group = group)) + 
       geom_point() + 
       stat_ellipse(type = "norm") +
       theme(legend.position='none') +
       theme_minimal() +
  labs(title = "PC1 vs PC2")

```

```{r}

fwrite(train_pca11, file.path("..", "..", "results", "Data_for_predictive_model", "train_pca_new_genes_allgroups.csv"))
```

```{r}
ggplot(data = train_pca11, aes(x = PC2, y = PC3, col = group, group = group)) +
       geom_point() +
       stat_ellipse(type = "norm") +
       theme(legend.position='none') +
       theme_minimal() +
  labs(title = "PC2 vs PC3")

```

```{r}

#Define training control
set.seed(123)
train.control = trainControl(method = "repeatedcv",
                             number = 4, repeats = 3,
                             savePredictions = T,
                             classProbs = T)
```

```{r}

# Train the model
pca.logist.model = train(group ~ PC1 + PC2 + PC3,
                         data = train_pca11,
                         method = "multinom",
                         trControl = train.control,
                         family = binomial())

```


```{r}
require(pROC)
p = plot.roc(pca.logist.model$pred$obs,
         pca.logist.model$pred$DM1)
ruc_dt = data.table(
  true_positive_rate = p$sensitivities,
  false_positive_rate = 1 - p$specificities
)
ggplot(ruc_dt, aes(x = false_positive_rate, y = true_positive_rate)) +
  geom_point()

```

```{r}

fwrite(ruc_dt, file = file.path("..", "..", "results", "Data_for_new_predictive_model_multinom", "train_ROC_new_genes_allgroups.csv"))
```

```{r}
pca.logist.model_pc1 = train(group ~ PC1,
                         data = train_pca11,
                         method = "multinom",
                         trControl = train.control,
                         family = binomial())
```

```{r}
# Summarize the results
print(pca.logist.model)
print(pca.logist.model_pc1)

plot(pca.logist.model, main="Model Accuracies with MARS")
print(pca.logist.model_pc1, main="Model Accuracies with MARS")

plot(varImp(pca.logist.model), main="Variable Importance")
```

```{r}

# test data
test_pca = predict(
  preProcess(test, method = c("center", "scale", "pca"), verbose = TRUE, pcaComp = 3),
  test
)
test_predict = predict(pca.logist.model, test_pca)

test_predict_pc1 = predict(pca.logist.model_pc1, test_pca)
```

```{r}
## confusionMatrix
confusionMatrix(reference = test$group, data = test_predict,
                mode='everything', positive='DM1')
confusionMatrix(reference = test$group, data = test_predict_pc1,
                mode='everything', positive='DM1')
```



```{r}
require(cluster)
require(ggfortify)
ggplot(data = test_pca, aes(x = PC1, y = PC2, col = group, group = group)) + 
       geom_point() + 
       stat_ellipse(type = "norm") +
       theme(legend.position='none') +
       theme_minimal() +
  labs(title = "PC1 vs PC2")
```

